import React from 'react';

import '@/styles/globals.css';
import NavbarCommon from '@/components/NavbarCommon';

export const metadata = {
  title: 'GSO | Dashboard',
  description: 'Generated by Next.js'
};

export default function DashboardLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <NavbarCommon />
        {children}
      </body>
    </html>
  );
}
