import '@/styles/globals.css';
import React from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function PrivateLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
